*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 06.04.2020 at 19:17:58
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZYB_SD_V_C007...................................*
FORM GET_DATA_ZYB_SD_V_C007.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZYB_SD_T_C007 WHERE
(VIM_WHERETAB) .
    CLEAR ZYB_SD_V_C007 .
ZYB_SD_V_C007-MANDT =
ZYB_SD_T_C007-MANDT .
ZYB_SD_V_C007-VTWEG =
ZYB_SD_T_C007-VTWEG .
ZYB_SD_V_C007-WERKS =
ZYB_SD_T_C007-WERKS .
ZYB_SD_V_C007-ACT =
ZYB_SD_T_C007-ACT .
ZYB_SD_V_C007-SEQNO =
ZYB_SD_T_C007-SEQNO .
ZYB_SD_V_C007-KUNNR =
ZYB_SD_T_C007-KUNNR .
    SELECT SINGLE * FROM KNA1 WHERE
KUNNR = ZYB_SD_T_C007-KUNNR .
    IF SY-SUBRC EQ 0.
ZYB_SD_V_C007-NAME1 =
KNA1-NAME1 .
    ENDIF.
    SELECT SINGLE * FROM ZYB_SD_T_C006 WHERE
VTWEG = ZYB_SD_T_C007-VTWEG AND
WERKS = ZYB_SD_T_C007-WERKS .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T000.
      IF SY-SUBRC EQ 0.
      ENDIF.
      SELECT SINGLE * FROM T001W WHERE
WERKS = ZYB_SD_T_C006-WERKS .
      IF SY-SUBRC EQ 0.
ZYB_SD_V_C007-WERKS_TXT =
T001W-NAME1 .
      ENDIF.
      SELECT SINGLE * FROM TVTW WHERE
VTWEG = ZYB_SD_T_C006-VTWEG .
      IF SY-SUBRC EQ 0.
        SELECT SINGLE * FROM TVTWT WHERE
VTWEG = TVTW-VTWEG AND
SPRAS = SY-LANGU .
        IF SY-SUBRC EQ 0.
ZYB_SD_V_C007-VTEXT =
TVTWT-VTEXT .
        ENDIF.
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZYB_SD_V_C007.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZYB_SD_V_C007 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZYB_SD_V_C007.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZYB_SD_V_C007-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZYB_SD_T_C007 WHERE
  VTWEG = ZYB_SD_V_C007-VTWEG AND
  WERKS = ZYB_SD_V_C007-WERKS AND
  ACT = ZYB_SD_V_C007-ACT AND
  SEQNO = ZYB_SD_V_C007-SEQNO .
    IF SY-SUBRC = 0.
    DELETE ZYB_SD_T_C007 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZYB_SD_T_C007 WHERE
  VTWEG = ZYB_SD_V_C007-VTWEG AND
  WERKS = ZYB_SD_V_C007-WERKS AND
  ACT = ZYB_SD_V_C007-ACT AND
  SEQNO = ZYB_SD_V_C007-SEQNO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZYB_SD_T_C007.
    ENDIF.
ZYB_SD_T_C007-MANDT =
ZYB_SD_V_C007-MANDT .
ZYB_SD_T_C007-VTWEG =
ZYB_SD_V_C007-VTWEG .
ZYB_SD_T_C007-WERKS =
ZYB_SD_V_C007-WERKS .
ZYB_SD_T_C007-ACT =
ZYB_SD_V_C007-ACT .
ZYB_SD_T_C007-SEQNO =
ZYB_SD_V_C007-SEQNO .
ZYB_SD_T_C007-KUNNR =
ZYB_SD_V_C007-KUNNR .
    IF SY-SUBRC = 0.
    UPDATE ZYB_SD_T_C007 .
    ELSE.
    INSERT ZYB_SD_T_C007 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZYB_SD_V_C007-UPD_FLAG,
STATUS_ZYB_SD_V_C007-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZYB_SD_V_C007.
  SELECT SINGLE * FROM ZYB_SD_T_C007 WHERE
VTWEG = ZYB_SD_V_C007-VTWEG AND
WERKS = ZYB_SD_V_C007-WERKS AND
ACT = ZYB_SD_V_C007-ACT AND
SEQNO = ZYB_SD_V_C007-SEQNO .
ZYB_SD_V_C007-MANDT =
ZYB_SD_T_C007-MANDT .
ZYB_SD_V_C007-VTWEG =
ZYB_SD_T_C007-VTWEG .
ZYB_SD_V_C007-WERKS =
ZYB_SD_T_C007-WERKS .
ZYB_SD_V_C007-ACT =
ZYB_SD_T_C007-ACT .
ZYB_SD_V_C007-SEQNO =
ZYB_SD_T_C007-SEQNO .
ZYB_SD_V_C007-KUNNR =
ZYB_SD_T_C007-KUNNR .
    SELECT SINGLE * FROM KNA1 WHERE
KUNNR = ZYB_SD_T_C007-KUNNR .
    IF SY-SUBRC EQ 0.
ZYB_SD_V_C007-NAME1 =
KNA1-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZYB_SD_V_C007-NAME1 .
    ENDIF.
    SELECT SINGLE * FROM ZYB_SD_T_C006 WHERE
VTWEG = ZYB_SD_T_C007-VTWEG AND
WERKS = ZYB_SD_T_C007-WERKS .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T000.
      IF SY-SUBRC EQ 0.
      ELSE.
        CLEAR SY-SUBRC.
      ENDIF.
      SELECT SINGLE * FROM T001W WHERE
WERKS = ZYB_SD_T_C006-WERKS .
      IF SY-SUBRC EQ 0.
ZYB_SD_V_C007-WERKS_TXT =
T001W-NAME1 .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZYB_SD_V_C007-WERKS_TXT .
      ENDIF.
      SELECT SINGLE * FROM TVTW WHERE
VTWEG = ZYB_SD_T_C006-VTWEG .
      IF SY-SUBRC EQ 0.
        SELECT SINGLE * FROM TVTWT WHERE
VTWEG = TVTW-VTWEG AND
SPRAS = SY-LANGU .
        IF SY-SUBRC EQ 0.
ZYB_SD_V_C007-VTEXT =
TVTWT-VTEXT .
        ELSE.
          CLEAR SY-SUBRC.
          CLEAR ZYB_SD_V_C007-VTEXT .
        ENDIF.
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZYB_SD_V_C007-VTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZYB_SD_V_C007-WERKS_TXT .
      CLEAR ZYB_SD_V_C007-VTEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZYB_SD_V_C007 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZYB_SD_V_C007-VTWEG TO
ZYB_SD_T_C007-VTWEG .
MOVE ZYB_SD_V_C007-WERKS TO
ZYB_SD_T_C007-WERKS .
MOVE ZYB_SD_V_C007-ACT TO
ZYB_SD_T_C007-ACT .
MOVE ZYB_SD_V_C007-SEQNO TO
ZYB_SD_T_C007-SEQNO .
MOVE ZYB_SD_V_C007-MANDT TO
ZYB_SD_T_C007-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZYB_SD_T_C007'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZYB_SD_T_C007 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZYB_SD_T_C007'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZYB_SD_V_C007 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZYB_SD_T_C007-MANDT =
ZYB_SD_V_C007-MANDT .
ZYB_SD_T_C007-VTWEG =
ZYB_SD_V_C007-VTWEG .
ZYB_SD_T_C007-WERKS =
ZYB_SD_V_C007-WERKS .
ZYB_SD_T_C007-ACT =
ZYB_SD_V_C007-ACT .
ZYB_SD_T_C007-SEQNO =
ZYB_SD_V_C007-SEQNO .
ZYB_SD_T_C007-KUNNR =
ZYB_SD_V_C007-KUNNR .
    SELECT SINGLE * FROM KNA1 WHERE
KUNNR = ZYB_SD_T_C007-KUNNR .
    IF SY-SUBRC EQ 0.
ZYB_SD_V_C007-NAME1 =
KNA1-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZYB_SD_V_C007-NAME1 .
    ENDIF.
    SELECT SINGLE * FROM ZYB_SD_T_C006 WHERE
VTWEG = ZYB_SD_T_C007-VTWEG AND
WERKS = ZYB_SD_T_C007-WERKS .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T000.
      IF SY-SUBRC EQ 0.
      ELSE.
        CLEAR SY-SUBRC.
      ENDIF.
      SELECT SINGLE * FROM T001W WHERE
WERKS = ZYB_SD_T_C006-WERKS .
      IF SY-SUBRC EQ 0.
ZYB_SD_V_C007-WERKS_TXT =
T001W-NAME1 .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZYB_SD_V_C007-WERKS_TXT .
      ENDIF.
      SELECT SINGLE * FROM TVTW WHERE
VTWEG = ZYB_SD_T_C006-VTWEG .
      IF SY-SUBRC EQ 0.
        SELECT SINGLE * FROM TVTWT WHERE
VTWEG = TVTW-VTWEG AND
SPRAS = SY-LANGU .
        IF SY-SUBRC EQ 0.
ZYB_SD_V_C007-VTEXT =
TVTWT-VTEXT .
        ELSE.
          CLEAR SY-SUBRC.
          CLEAR ZYB_SD_V_C007-VTEXT .
        ENDIF.
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZYB_SD_V_C007-VTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZYB_SD_V_C007-WERKS_TXT .
      CLEAR ZYB_SD_V_C007-VTEXT .
    ENDIF.
ENDFORM.
